### ISSUE TITLE
Wrong aria role on Load More (pagination) demo element

### ISSUE THREAD

**Issue by nickshanks** [bbc/gel#110]
On a Mac, using Safari, with VoiceOver turned on, and with Javascript turned off (Develop menu, might need to enable it in the prefs first), load this page:

https://bbc.github.io/gef-docs/components/demos/load-more/

Navigate through the page with VO-Right Arrow until you get to the pagination links at the end (or just skip to the navigation landmark), and then go through each link until you get to the ellipsis. This has the ARIA role of "separator" which is intended to identify a grabable bar that allows a user to resize two panes within a window relative to one another.
It gets read out as "horizontal splitter, collapsed on top".
I don't know if there is an appropriate role to use here, or if simply removing the role would be best.

It would be nice if the pagination had a separate demo without needing to turn off javascript.

**Comment by micmath** [comment]
In some of our early prototypes for the demo pages we had a "See it unenhanced" button which would effectively disable all JS enhancements. That was pretty sweet, but actually in this case I think we should consider pagination to be like a component in it's own right, and have two demos for this page, one that shows the pagination on it's own. I'll open a separate ticket for that.

**Comment by Heydon** [comment]
https://chrome.google.com/webstore/detail/quick-javascript-switcher/geddoclleiomckbhadiaipdggiiccfje?hl=en

**Comment by micmath** [comment]
As the BBC, we would add, "Other browsers and browser extensions are available..." :-D

To be fair people might want to use pagination _instead_ of load more. Personaly I think load more should rule them all, but I'm not in charge of everyone yet, so I've asked @simonsinclair to have a go at building a second demo for that page which just show pagination.

**Comment by Heydon** [comment]
> ARIA role of "separator" which is intended to identify a grabable bar that allows a user to resize two panes within a window relative to one another.

Not sure where this definition comes from, but I am using in line with the definition here: https://www.w3.org/WAI/PF/aria/roles#separator. It is announced as _"horizontal splitter"_, which is what it does visually in my view, so is reasonably apt. It could, however, simply be removed from AT readout with `aria-hidden="true"`.

**Comment by micmath** [comment]
From [WAI ARIA 1.1](https://www.w3.org/TR/wai-aria-1.1/#separator)

> There are two types of separators: a static structure that provides only a visible boundary and a focusable, interactive widget that is also moveable. If a separator is not focusable, it is revealed to assistive technologies as a static structural element. For example, a static separator can be used to help visually divide two groups of menu items in a menu or to provide a horizontal rule between two sections of a page.

So you are both right?

**Comment by micmath** [comment]
The element in question, `<li role="separator">&hellip;</li>`, in this case cannot receive focus, so it seems like Safari with VoiceOver is being different from what WAI ARIA say (the element should be treated as not interactive). Do other screen readers behave as expected?

**Comment by Heydon** [comment]
Yes, I think so. I'm using it in the non-interactive sense. It should not be focusable in that case, and is not.

**Comment by nickshanks** [comment]
As a Cocoa developer for ten years, "splitter" has a specific meaning (the grabbable divider between two panes) which quite possibly Apple's developers have mis-interpreted.

**Comment by micmath** [comment]
@nickshanks, suggested resolution? This seems like a bug in the client software rather than the example code, but possibly we should accommodate that bug?

**Comment by nickshanks** [comment]
@micmath Fair enough, I shall report it to Apple. I don't see why it needs to have a role at all, to be honest.

**Comment by nickshanks** [comment]
> To be fair people might want to use pagination instead of load more. Personaly I think load more should rule them all

As I see it, pagination is useful over load more in two regards:
1) Skipping far ahead (especially when results are sorted on factors other than relevance, e.g. alphabetically without start-letter links, or some numerical value and you know the result you're looking for is many pages away). You can either click a page link to skip several pages, or hack the URL.
2) Saving/sharing a link to a specific group of results which are not the first set.

The load more concept works when when results are sorted by relevance, or have no discernible ordering.

**Comment by micmath** [comment]
Closing as no further activity in the 6 months since it was opened.
