### ISSUE TITLE
Add pagination demo to load-more docs

### ISSUE THREAD

**Issue by micmath** [bbc/gel#111]
I think we should consider pagination to be like a component in it's own right, and have two demos for this page, one that shows the pagination on it's own.

refers to #110

**Comment by micmath** [comment]
ref comments posted by @nickshanks in https://github.com/bbc/gef-docs/issues/110#issuecomment-503069557

**Comment by simonsinclair** [comment]
See pull request https://github.com/bbc/gef-docs/pull/115.

**Comment by simonsinclair** [comment]
Closing, because the PR was merged.
