### ISSUE TITLE
Promo - not always related content

### ISSUE THREAD

**Issue by EmmaJP** [bbc/gel#72]
I noticed the current version of Promos documentation recommends a group of promos are collected within an `<aside>` element. While I entirely agree with this for complementary reading on a content page, it does not cover the use case of promos on an index page, where the entire content of that page is groups of promos and use of `<aside>` as the containing element would be incorrect.

It would be good if the Promos stuff covered both scenarios. In an index page situation something like the following might be more appropriate (div or section depending on situation):

```
<h1>Content title</h1>
<div role="region" aria-labelled-by="region1">
  <h2 id="region1">New today</h2>
  <!-- promo list -->
</div>
<div role="region" aria-labelled-by="region2">
  <h2 id="region2">Recommended for you</h2>
  <!-- promo list -->
</div>
```

**Comment by micmath** [comment]
This makes sense to me. The WHATWG says:

> The aside element represents a section of a page that consists of content that is tangentially related to the content around the aside element, and which could be considered separate from that content. Such sections are often represented as sidebars in printed typography.

It's debatable what the *related* content around the aside element would be on a homepage or 
 portal page, where _everything_ is callout to go to other pages. But in debatable cases then I think giving the developer the choice is the best way to go.

@EmmaJP would you like to update that page and send a pull request with your added advice please?
