### ISSUE TITLE
Promo, and others - list constituent parts and/or data required to function

### ISSUE THREAD

**Issue by simonsinclair** [bbc/gel#97]
_This issue is a part of a series._

**Can we avoid sending developers to GEL _design_ documentation to read what components are composed of?** As a developer, I want to know what a component is comprised of (the smaller components I'm going to have to build, if any) and the data required for it to function.

There are multiple ways we could do this, but one (keeping things agnostic) could be to list the data required for it to function. In React JS, Vue JS etc, these would translate to properties.

In React a simple Promo component may look like this: 
```
function Promo(props) {
  return <h2 href={props.href}>{props.heading}</h2>;
}
```
Note the use of `props`

An example of a list of data required for a Promo could look like this:
- headline
- href
- image source
- description

**Comment by micmath** [comment]
I think this is a good idea, @simonsinclair 

I propose we add a distinct section with it's own heading for each component, where we can list the expected content data, and their variations.

Would you care to do a pull request for this, using the Promo component as a first try?

**Comment by micmath** [comment]
BTW it is not verboten to send developers to GEL, the line between GEF and GEL is intentionally fluid. There are plenty of good reasons for developers to read GEL and for designers to read GEF, but I get what you mean about having the _properties_ of the component explained in the same document :-)

**Comment by simonsinclair** [comment]
Yes, sure. I'll take a stab at creating a distinct section for the Promo.

**Comment by micmath** [comment]
We usually have these sections:

```
Introduction
Recommended markup
Recommended layout
Recommended behaviour
Example implementation
Related research
```

I would suggest we add a new section right after 'Introduction'. We could call it 'Content properties'?

**Comment by simonsinclair** [comment]
'Content properties' is a good title.

In terms of structure, how would you feel about something like this?

| Property |  Required | Example |
| ------ |  ------------ | -------- |
| Headline | Yes | `Is this whale a Russian spy?` |
| `href`  |  Yes | `https://www.bbc.co.uk/news/av/world-europe-48100700/russian-spy-whale` | 
| ...  | | |

**Comment by micmath** [comment]
I really hope that whale is _not_ a Russian spy.

It might tricky to say what's required on a _per property_ basis like that. For example I could imagine various combinations of properties that would be acceptable, as long as you had some combination -- I don't think a mere text and href would be a "promo"? Or would it? That's just literally a link surely?

But a name, description (to add?) and example seem like obvious things to document. You can try going with the `required` column and maybe it will be fine.

**Comment by simonsinclair** [comment]
He looks a bit suspect...

I took a stab and combined our points into a pull request (#103). Let me know what you think.

**Comment by simonsinclair** [comment]
Closing, because the PR was merged.
